### ISSUE TITLE
Compile error in Arduino 1.5.7

### ISSUE THREAD

**Issue by bnadeau** [fabule/Clyde#4]
compiler.path value is not set correctly in the platform.txt file to configure Clyde as a board.
But even with that variable set, the IDE shows this error:
avr-g++.exe: no input files

The input file seems to be correct when looking at the verbose output.

**Comment by angelagabereau** [comment]
I did a few things to make the 1.5 version of the hardware compatible with Aruduino 1.5.7
1. platfoorm,txt Set compiler path to correct path, compiler.path={runtime.ide.path}/hardware/tools/avr/bin/
2. boards.txt Add the Fabule to the usb product name.  Strange, I know. clyde.build.usb_product="Fabule Clyde"
3. Add the avr specific libraries to the fabule hardware folder.  That is Wire, SPI, SoftwareSerial and EEPROM.
